// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm1uzvwhPuJePqM0_4gQV97jAi-LRwohc',
    appId: '1:129982777312:web:d9db8c06af7b10119c8d85',
    messagingSenderId: '129982777312',
    projectId: 'smartproject-c2663',
    authDomain: 'smartproject-c2663.firebaseapp.com',
    storageBucket: 'smartproject-c2663.firebasestorage.app',
    measurementId: 'G-VZ2KSMT3L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH8RJJ8UA_hoCZRddgdY9IDCgRy-NTgc8',
    appId: '1:129982777312:android:94d1d1cee70b0a8b9c8d85',
    messagingSenderId: '129982777312',
    projectId: 'smartproject-c2663',
    storageBucket: 'smartproject-c2663.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdfAUZRwdDkYXQQ5ba8c5jqPCi-v-sIAs',
    appId: '1:129982777312:ios:c95ccb087975ba239c8d85',
    messagingSenderId: '129982777312',
    projectId: 'smartproject-c2663',
    storageBucket: 'smartproject-c2663.firebasestorage.app',
    iosBundleId: 'com.example.smartReport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdfAUZRwdDkYXQQ5ba8c5jqPCi-v-sIAs',
    appId: '1:129982777312:ios:c95ccb087975ba239c8d85',
    messagingSenderId: '129982777312',
    projectId: 'smartproject-c2663',
    storageBucket: 'smartproject-c2663.firebasestorage.app',
    iosBundleId: 'com.example.smartReport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm1uzvwhPuJePqM0_4gQV97jAi-LRwohc',
    appId: '1:129982777312:web:37c74d97bae7d4899c8d85',
    messagingSenderId: '129982777312',
    projectId: 'smartproject-c2663',
    authDomain: 'smartproject-c2663.firebaseapp.com',
    storageBucket: 'smartproject-c2663.firebasestorage.app',
    measurementId: 'G-E9W3R6ESZX',
  );
}
